name: Build Application Packages

on:
  push:
    branches:
      - upgraded-to-app

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Windows EXE
        run: |
          pyinstaller --onefile --icon=cse.logo.ico src/turnin.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-package-exe
          path: dist/turnin.exe

  build-debian-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Prepare Debian package directory
        run: |
          mkdir -p turnin/DEBIAN
          echo "Package: turnin" >> turnin/DEBIAN/control
          echo "Version: 3.3" >> turnin/DEBIAN/control
          echo "Architecture: all" >> turnin/DEBIAN/control
          echo "Maintainer: Pavlos Orfanidis <pavlos@orfanidis.net.gr>" >> turnin/DEBIAN/control
          echo "Description: TurnIn App" >> turnin/DEBIAN/control
          echo "Depends: python3-sshtunnel, python3-paramiko, python3-sentry-sdk, python3-pyqt6, python3-requests" >> turnin/DEBIAN/control

          mkdir -p turnin/usr/bin
          cp src/turnin.py turnin/usr/bin
          chmod +x turnin/usr/bin/turnin.py

          mkdir -p turnin/usr/share/applications
          echo "[Desktop Entry]" >> turnin/usr/share/applications/turnin.desktop
          echo "Name=TurnIn" >> turnin/usr/share/applications/turnin.desktop
          echo "Exec=python3 /usr/bin/turnin.py" >> turnin/usr/share/applications/turnin.desktop
          echo "Icon=/usr/share/icons/cse.logo.png" >> turnin/usr/share/applications/turnin.desktop
          echo "Type=Application" >> turnin/usr/share/applications/turnin.desktop

          mkdir -p turnin/usr/share/icons
          cp cse.logo.png turnin/usr/share/icons

      - name: Build Debian package
        run: dpkg-deb --build turnin

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-package-deb
          path: turnin.deb