name: Build Application Packages

on:
  push:
    branches:
      - upgraded-to-app

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install keyring cryptography
          pip install -r requirements.txt

      - name: Create hook file
        run: |
          mkdir -p hooks
          @'
          from PyInstaller.utils.hooks import collect_all

          # Add these modules as hidden imports
          hiddenimports = [
              'keyring',
              'keyring.backends',
              'cryptography',
              'paramiko',
              'sshtunnel',
              'sentry_sdk'
          ]

          # Collect submodules
          datas, binaries, more_imports = collect_all('keyring')
          hiddenimports.extend(more_imports)
          '@ > hooks/hook-extras.py

      # Create a separate script that fixes imports in Python files
      - name: Fix imports in Python files
        shell: powershell
        run: |
          $files = Get-ChildItem -Path src -Include *.py -Recurse
          foreach ($file in $files) {
            $content = Get-Content -Path $file.FullName
            $newContent = $content -replace 'from src\.', 'from ' -replace 'from ..', 'from src.'
            Set-Content -Path $file.FullName -Value $newContent
          }

      - name: Build Windows EXE
        run: |
          pyinstaller --name turnin --onefile --windowed --icon=cse.logo.ico ^
            --add-data "cse.logo.png;." ^
            --additional-hooks-dir=hooks ^
            --hidden-import=keyring ^
            --hidden-import=cryptography ^
            --hidden-import=sentry_sdk ^
            --hidden-import=paramiko ^
            --hidden-import=sshtunnel ^
            src/turnin.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-packages-exe
          path: dist/turnin.exe

  build-debian-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Fix imports in Python files
        run: |
          # Create a backup of the original files
          mkdir -p backup_src
          cp -r src backup_src/
          
          # Find and fix all import statements
          find src -name "*.py" -exec sed -i 's/from src\./from /g' {} \;
          find src -name "*.py" -exec sed -i 's/from \.\./from src./g' {} \;

      - name: Prepare Debian package directory
        run: |
          mkdir -p turnin/DEBIAN
          # Create control file
          cat > turnin/DEBIAN/control << EOF
          Package: turnin
          Version: 3.3
          Architecture: all
          Maintainer: Pavlos Orfanidis <pavlos@orfanidis.net.gr>
          Description: TurnIn App for submitting assignments
          Depends: python3-sshtunnel, python3-paramiko, python3-sentry-sdk, python3-pyqt6, python3-requests, python3-keyring, python3-cryptography
          EOF
          
          # Create postinst script to set proper permissions
          cat > turnin/DEBIAN/postinst << EOF
          #!/bin/sh
          chmod 755 /usr/bin/turnin
          mkdir -p /var/log/turnin
          chmod 777 /var/log/turnin
          exit 0
          EOF
          chmod +x turnin/DEBIAN/postinst
          
          # Create logs directory
          mkdir -p turnin/var/log/turnin
          chmod 777 turnin/var/log/turnin
          
          # Create wrapper script that includes PYTHONPATH
          mkdir -p turnin/usr/bin
          cat > turnin/usr/bin/turnin << EOF
          #!/bin/bash
          export PYTHONPATH=/usr/share/turnin
          python3 /usr/share/turnin/turnin.py "\$@"
          EOF
          chmod +x turnin/usr/bin/turnin
          
          # Create application directory
          mkdir -p turnin/usr/share/turnin
          
          # Copy all Python files preserving original structure
          cp -r src/* turnin/usr/share/turnin/
          
          # Create empty __init__.py files for proper package structure
          find turnin/usr/share/turnin -type d -exec touch {}/__init__.py \;
          
          # Copy resources
          cp cse.logo.png turnin/usr/share/turnin/
          
          # Create desktop file
          mkdir -p turnin/usr/share/applications
          cat > turnin/usr/share/applications/turnin.desktop << EOF
          [Desktop Entry]
          Name=TurnIn
          Exec=/usr/bin/turnin
          Icon=/usr/share/icons/turnin/cse.logo.png
          Type=Application
          Categories=Education;Development;
          EOF
          
          # Copy icon
          mkdir -p turnin/usr/share/icons/turnin
          cp cse.logo.png turnin/usr/share/icons/turnin/

      - name: Build Debian package
        run: dpkg-deb --build turnin

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-packages-deb
          path: turnin.deb