name: Build Application Packages

on:
  push:
    branches:
      - upgraded-to-app

jobs:
  build-windows-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Create entry script
        run: |
          # Create a main entry script that properly sets up the path
          @'
          import os
          import sys

          # Add the current directory to path
          base_dir = os.path.abspath(os.path.dirname(sys.argv[0]))
          sys.path.insert(0, base_dir)

          # Import the main function from src.turnin
          from src.turnin import main

          if __name__ == "__main__":
              main()
          '@ > main_entry.py

      - name: Build Windows EXE
        run: |
          pyinstaller --name turnin --onefile --windowed --icon=cse.logo.ico --add-data "cse.logo.png;." --add-data "src;src" main_entry.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-package-exe
          path: dist/turnin.exe

  build-debian-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Prepare Debian package directory
        run: |
          mkdir -p turnin/DEBIAN
          # Create control file
          cat > turnin/DEBIAN/control << EOF
          Package: turnin
          Version: 3.3
          Architecture: all
          Maintainer: Pavlos Orfanidis <pavlos@orfanidis.net.gr>
          Description: TurnIn App for submitting assignments
          Depends: python3-sshtunnel, python3-paramiko, python3-sentry-sdk, python3-pyqt6, python3-requests
          EOF

          # Create postinst script to set proper permissions
          cat > turnin/DEBIAN/postinst << EOF
          #!/bin/sh
          chmod 755 /usr/bin/turnin
          exit 0
          EOF
          chmod +x turnin/DEBIAN/postinst

          # Create main entry script
          mkdir -p turnin/usr/share/turnin
          cat > turnin/usr/share/turnin/main.py << EOF
          import os
          import sys

          # Add the directory to path
          base_dir = os.path.abspath(os.path.dirname(__file__))
          sys.path.insert(0, base_dir)

          # Import the main function
          from src.turnin import main

          if __name__ == "__main__":
              main()
          EOF

          # Create wrapper script for proper execution
          mkdir -p turnin/usr/bin
          cat > turnin/usr/bin/turnin << EOF
          #!/bin/bash
          python3 /usr/share/turnin/main.py "\$@"
          EOF
          chmod +x turnin/usr/bin/turnin

          # Copy all source files
          mkdir -p turnin/usr/share/turnin/src
          cp -r src/* turnin/usr/share/turnin/src/
          # Make sure we have __init__.py files for proper package imports
          touch turnin/usr/share/turnin/src/__init__.py
          find turnin/usr/share/turnin/src -type d -exec touch {}"/__init__.py" \;
          
          # Copy resources
          cp cse.logo.png turnin/usr/share/turnin/

          # Create desktop file
          mkdir -p turnin/usr/share/applications
          cat > turnin/usr/share/applications/turnin.desktop << EOF
          [Desktop Entry]
          Name=TurnIn
          Exec=/usr/bin/turnin
          Icon=/usr/share/icons/turnin/cse.logo.png
          Type=Application
          Categories=Education;Development;
          EOF

          # Copy icon
          mkdir -p turnin/usr/share/icons/turnin
          cp cse.logo.png turnin/usr/share/icons/turnin/

      - name: Build Debian package
        run: dpkg-deb --build turnin

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-package-deb
          path: turnin.deb